### ISSUE TITLE
devicePixelRatio not added to POST call (toBinary and toFile)

### ISSUE THREAD

**Issue by arnaudgoulpeau** [typpo/quickchart-php#10]
Since devicePixelRatio is defaulted to 2 in API, the resulting image is x2 on height and width.

The devicePixelRatio is ok on getUrk, getShortUrl, but not on toBinary and toFile.

To be able to put a devicePixelRatio to 1, without divide entry height and with, toBinary method should use the devicePixelRatio as it does for heigh and width

**Comment by arnaudgoulpeau** [comment]
I am preparing a PR for that right now

**Comment by typpo** [comment]
Thanks for catching this!

**Comment by typpo** [comment]
Your fix is released in v1.2.2

**Comment by arnaudgoulpeau** [comment]
Thank you !
