### ISSUE TITLE
Access status code returned by QuickCharts

### ISSUE THREAD

**Issue by Ceepster14** [typpo/quickchart-php#12]
Hi,

I'm using this package in a Laravel project which is going to produce a number of charts from a queued Job which then incorporates them into a PDF which is then emailed to a user. 

From the QuickChart documentation i see that it will return a non-200 status code if there was an error when generating the chart. 

As the charts are being generated in the background, I need a way to programmatically ascertain whether, as far as QuickCharts is concerned, it has received a well-formed config and has generated the chart, which I can probably do from the returned status code.

I've seen from my testing, if QuickChart receives an incorrect config file, it does return an image containing the error rendered into the image, so I can't use whether or not the code gets an image returned as an indicator of success or failure.

Do you have any suggestions as to a robust method whereby I can check the status code or any other mechanisms I could use?

Thanks

**Comment by typpo** [comment]
In the latest release, the function will now throw an error when chart generation fails.  I believe that solves your need of programmatically detecting success vs failure.  Let me know if you need anything else!

**Comment by Ceepster14** [comment]
Hi Ian,

Thanks for the fix. I'll give it a try!

Cheers

Chris
