### ISSUE TITLE
getShortUrl throws SSL certificate problem

### ISSUE THREAD

**Issue by peroanjo** [typpo/quickchart-php#6]
Hi, when I'm using getUrl() the library works perfectly however when using getShortUrl() it throws the following error:

```
PHP Fatal error:  Uncaught Exception: SSL certificate problem: unable to get local issuer certificate in C:\inetpub\wwwroot\phppr\dataset.php:167
Stack trace:
#0 C:\inetpub\wwwroot\phppr\dataset.php(66): QuickChart->getShortUrl()
#1 {main}
```

**Comment by typpo** [comment]
You need to configure PHP to use SSL properly.  This involves updating php.ini.  Here's an [example](https://stackoverflow.com/a/35051707/3219919)
